// Generated by CoffeeScript 1.3.3
(function() {
  var docco,
    _this = this;

  docco = require('docco');

  process.on('message', function(data) {
    return docco.document(data.sources, data.options, function(err) {
      if (err) {
        return process.send({
          err: true,
          sources: data.sources
        });
      } else {
        return process.send({
          err: false,
          sources: data.sources
        });
      }
    });
  });

}).call(this);
